# Generated by Django 4.2 on 2026-05-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Holiday Party', 'Holiday Party'), ('Private Event', 'Private Event')], max_length=50)),
                ('event_date', models.DateField()),
                ('guests', models.CharField(choices=[('Under 25', 'Under 25'), ('25-50', '25-50'), ('50-100', '50-100'), ('100-200', '100-200'), ('200+', '200+')], max_length=50)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
