# Generated by Django 4.2 on 2026-05-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='cuisine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='dietary_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='flexible_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='hear_about',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='indoor_outdoor',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Food Only', 'Food Only'), ('Servers', 'Servers'), ('Delivery', 'Delivery'), ('Delivery & Setup', 'Delivery & Setup')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Holiday Party', 'Holiday Party'), ('Cultural Event', 'Cultural Event'), ('Other', 'Other')], max_length=50),
        ),
    ]
