# Generated by Django 4.2 on 2026-05-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_budget_inquiry_cuisine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='indoor_outdoor',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Quoted', 'Quoted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='cuisine',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Buffet', 'Buffet'), ('Plated/Seated', 'Plated/Seated'), ('Family Style', 'Family Style'), ('Stations', 'Stations'), ('Cocktail/Appetizers', 'Cocktail/Appetizers'), ('Drop-off', 'Drop-off')], max_length=100, null=True),
        ),
    ]
