# Generated by Django 4.2 on 2026-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_remove_inquiry_indoor_outdoor_inquiry_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='notes',
            new_name='event_details',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='service_type',
            new_name='service_style',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='indoor_outdoor',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='services_needed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Holiday Party', 'Holiday Party'), ('Cultural/Religious Celebration', 'Cultural/Religious Celebration'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Quoted', 'Quoted'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='New', max_length=30),
        ),
    ]
