# Generated by Django 4.2 on 2026-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_rename_notes_inquiry_event_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Quote Sent', 'Quote Sent'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='New', max_length=50),
        ),
    ]
