# Generated by Django 4.2 on 2026-05-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_inquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress'), ('Quote Sent', 'Quote Sent'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=50),
        ),
    ]
