# Generated by Django 4.2 on 2026-05-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0006_inquiry_updated_alter_inquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='hear_about',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Google Search', 'Google Search'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Friend / Family', 'Friend / Family'), ('Referral', 'Referral'), ('Advertisement', 'Advertisement'), ('Website', 'Website'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
