# Generated by Django 4.2 on 2026-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_eventservice_eventpackage_eventmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='business_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='google_map',
            field=models.URLField(blank=True, null=True),
        ),
    ]
