# Generated by Django 4.2 on 2026-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
