# Generated by Django 4.2 on 2026-05-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_offerpackage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
