# Generated by Django 4.2 on 2026-05-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_eventservice_image_alter_eventservice_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
